### ISSUE TITLE
RF production problem

### ISSUE THREAD

**Issue by DatrixTHLK** [CobbleWorksMC/CobbleWorks#1]
Hi,
I like where this mod is headed. Great for skyblock type maps. However, I've noticed a problem with the tier 1 CobbleGen. When upgrading to a tier 1 from tier 0 the production of cobblestone stops as the progress bar is stuck at 0. I put a NeoTech Furnace gen next to it just to see if the furnace gen would generate any RF for the cobblegen...negative. I tried using a solar panel II from solar flux reborn to generate RF for it...negative. Is there no way to produce RF for the Cobble Gen?

Cobbleworks 1.3.1 
Minecraft 1.10.2 
Forge 12.18.3.2185 

tier 0 doesn't need any RF to work.

**Comment by CobbleWorksMC** [comment]
This one may be my forge being out of date. I do not plug directly into any standardized RF API, instead the block uses the forge energy capabilities. Many mods use it, and I've gotten it to work with Ender IO so far, but I'll look into expanding it to be more inclusive.

**Comment by DatrixTHLK** [comment]
Well I'll see if Forge has updated, but I thought 2185 was the latest version they had out at the moment...
Edit: Yes, 2185 is the most recent version of forge. I'll use Ender IO for the time being then, Thanks for the response.

**Comment by CobbleWorksMC** [comment]
To be fair, my forge install is about a hundred versions behind. I should be the one to update, and I probably will at some point.

**Comment by DatrixTHLK** [comment]
Oh, I see. YOUR forge is out of date not Forge themselves. I understand now
