### ISSUE TITLE
Server crash on startup 1.12.0-2.0

### ISSUE THREAD

**Issue by n-rosati** [CobbleWorksMC/CobbleWorks#3]
Version 2.0 crashes server on server startup. Tested with Forge 2443 and 2387 and both crash. 
[forge 2387 crash report.txt](https://github.com/CobbleWorksMC/CobbleWorks/files/1225800/forge.2387.crash.report.txt)
[forge 2443 crash report.txt](https://github.com/CobbleWorksMC/CobbleWorks/files/1225801/forge.2443.crash.report.txt)

**Comment by CobbleWorksMC** [comment]
Uploaded version 2.1 which should fix this issue. Let me know if it works or still occurs, until then I'll keep this issue open.

**Comment by n-rosati** [comment]
2.1 seems to have fixed the problem, thanks!
